server:
  port: 8888
  
spring:
  application:
    name: gateway-zuul

eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
    
zuul:
  host:
    connect-timeout-millis: 5000000 
    socket-timeout-millis: 5000000     
  routes:
    classroom:
      url: http://localhost:8082/
    student:
      url: http://localhost:8081/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS  